# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Will Power' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for Will Power
  pod 'AFNetworking', '~> 3.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'FMDB', '~> 2.7.2'
  pod 'Reachability', '~> 3.2'
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'FlatUIKit', '~> 1.6.2'
  pod 'JazzHands', '~> 2.0.8'
  pod 'TSMessages', '~> 0.9.12'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'JVFloatLabeledTextField', '~> 1.2.1'
  pod 'SCLAlertView-Objective-C', '~> 1.1.3'
  # U-Share SDK UI模块（分享面板，建议添加）
  pod ‘UMengUShare/UI’
  # 集成微信(完整版14.4M)
  pod ‘UMengUShare/Social/WeChat'

  pod 'lottie-ios', '~> 2.5.0'

  
  target 'Will PowerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Will PowerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
